### DISCUSSION TITLE
Successful integrated evcc

### DISCUSSION THREAD

**Discussion by azabold-priv** [alienatedsec/solis-ha-modbus-cloud#25] [Show and tell]
Many thanks for these great instructions.
This enabled me to create a solution for photovoltaic surplus charging with my Solis inverter, my Easee wallbox (https://easee.com/) and evcc (https://evcc.io/en/).
My original attempt via SolisCloud was much too slow to achieve a reasonable control due to the 5-minute update interval.

![image](https://github.com/alienatedsec/solis-ha-modbus-cloud/assets/60702744/ff1f6149-851f-4e0b-a7e9-2d0b6e3c2dcb)

If anyone is interested in integrating evcc, I have the configuration of evcc.yaml for the Solis connection below:
```
meters:
- type: custom
  name: solis_grid
  power:
    source: modbus
    id: 1
    uri: 192.168.1.***:502
    rtu: false
    register:
      address: 33130
      type: input # holding or input
      decode: int32 # int16|32|64, uint16|32|64, float32|64 and u|int32s + float32s
    scale: -1.0 # floating point factor applied to result, e.g. for kW to W conversion
    timeout: 2s # timeout, without unit in ns

- type: custom
  name: solis_pv
  power:
    source: modbus
    id: 1
    uri: 192.168.1.***:502
    rtu: false
    register:
      address: 33057
      type: input # holding or input
      decode: int32 # int16|32|64, uint16|32|64, float32|64 and u|int32s + float32s
    #scale: -1.0 # floating point factor applied to result, e.g. for kW to W conversion
    timeout: 2s # timeout, without unit in ns

- type: custom
  name: solis_battery
  soc:
    source: modbus
    id: 1
    uri: 192.168.1.***:502
    rtu: false
    register:
      address: 33139
      type: input # holding or input
      decode: int16 # int16|32|64, uint16|32|64, float32|64 and u|int32s + float32s
    #scale: -1.0 # floating point factor applied to result, e.g. for kW to W conversion
    timeout: 2s # timeout, without unit in ns
  power:
    source: modbus
    id: 1
    uri: 192.168.1.***:502
    rtu: false
    register:
      address: 33149
      type: input # holding or input
      decode: int32 # int16|32|64, uint16|32|64, float32|64 and u|int32s + float32s
    scale: -1.0 # floating point factor applied to result, e.g. for kW to W conversion
    timeout: 2s # timeout, without unit in ns

site:
  title: Zuhause
  meters:
    grid: solis_grid
    pv: solis_pv
    battery: solis_battery
  residualPower: 0
  bufferSoc: 90
  prioritySoc: 80
```
