### DISCUSSION TITLE
Automation of charge time entities not working, but do work ok on a card

### DISCUSSION THREAD

**Discussion by Ian-Johnston** [alienatedsec/solis-ha-modbus-cloud#41] [General]
I have my Waveshare devices working, I have added the following two entities to a card and can confirm the inverter is accepting the values (soliscloud.com is updating correctly).
time.rai_3k_48es_5g_solis_time_charging_charge_start_slot_1
time.rai_3k_48es_5g_solis_time_charging_charge_end_slot_1

However, when I try to change these in automation.yaml it fails. I have tried several different ways and I just can't make changes to these two. I want the code to change the charge times as if the user had done it via the card.

Any ideas?........maybe writing to the modbus registers direct (I tried but couldn't get the code right for that).

The code below uses a couple of helpers, and they change just fine, just not the entities.

Ian.

```
# Battery inverter charge time strart/end (based on solar.forecast)
- alias: "Set Overnight Charging Schedule"
  description: "Determines overnight charging time based on tomorrow's solar forecast"
  mode: single
  trigger:
    - platform: time
      at: "23:30:00"
  action:
    - variables:
        solar_forecast: "{{ states('sensor.energy_production_tomorrow') | float(0) }}"

    - choose:
        - conditions:
            - condition: numeric_state
              entity_id: sensor.energy_production_tomorrow
              below: 3
          sequence:
            - service: input_datetime.set_datetime
              target:
                entity_id: input_datetime.charge_start
              data:
                time: "02:00"
            - service: input_datetime.set_datetime
              target:
                entity_id: input_datetime.charge_end
              data:
                time: "05:30"

        - conditions:
            - condition: numeric_state
              entity_id: sensor.energy_production_tomorrow
              below: 5
          sequence:
            - service: input_datetime.set_datetime
              target:
                entity_id: input_datetime.charge_start
              data:
                time: "02:00"
            - service: input_datetime.set_datetime
              target:
                entity_id: input_datetime.charge_end
              data:
                time: "05:00"

        - conditions:
            - condition: numeric_state
              entity_id: sensor.energy_production_tomorrow
              below: 7
          sequence:
            - service: input_datetime.set_datetime
              target:
                entity_id: input_datetime.charge_start
              data:
                time: "02:00"
            - service: input_datetime.set_datetime
              target:
                entity_id: input_datetime.charge_end
              data:
                time: "04:30"

        - conditions:
            - condition: numeric_state
              entity_id: sensor.energy_production_tomorrow
              below: 9
          sequence:
            - service: input_datetime.set_datetime
              target:
                entity_id: input_datetime.charge_start
              data:
                time: "02:00"
            - service: input_datetime.set_datetime
              target:
                entity_id: input_datetime.charge_end
              data:
                time: "04:00"

        - conditions:
            - condition: numeric_state
              entity_id: sensor.energy_production_tomorrow
              below: 12
          sequence:
            - service: input_datetime.set_datetime
              target:
                entity_id: input_datetime.charge_start
              data:
                time: "02:00"
            - service: input_datetime.set_datetime
              target:
                entity_id: input_datetime.charge_end
              data:
                time: "03:30"

      default:
        - service: input_datetime.set_datetime
          target:
            entity_id: input_datetime.charge_start
          data:
            time: "00:00"
        - service: input_datetime.set_datetime
          target:
            entity_id: input_datetime.charge_end
          data:
            time: "00:00"

    # Force Home Assistant to update the values
    - service: homeassistant.update_entity
      target:
        entity_id:
          - input_datetime.charge_start
          - input_datetime.charge_end

    # Log values to Home Assistant's system log
    - service: system_log.write
      data:
        message: >
          "Overnight Charging: Start Time - {{ states('input_datetime.charge_start') }}, 
          End Time - {{ states('input_datetime.charge_end') }}, 
          Solar Forecast - {{ solar_forecast }} kWh"
        level: info

    # Send a persistent notification with the values
    - service: persistent_notification.create
      data:
        title: "🔋 Overnight Charging Set"
        message: >
          Charging Schedule Updated:
          - Start: {{ states('input_datetime.charge_start') }}
          - End: {{ states('input_datetime.charge_end') }}
          - Solar Forecast: {{ solar_forecast }} kWh
        notification_id: "charging_schedule_update"

    # Send updated values to Solis
    - service: homeassistant.update_entity
      target:
        entity_id:
          - time.rai_3k_48es_5g_solis_time_charging_charge_start_slot_1
          - time.rai_3k_48es_5g_solis_time_charging_charge_end_slot_1
```

**Comment by sdgelectronics** [comment]
👌

**Comment by Ian-Johnston** [comment]
Got this working......subject to full testing for all weathers.

I modified the solis_modbus integration to expose a custom service (solis_modbus.set_time) that triggers the same internal update logic as my Lovelace card. Then, in automation.yaml, I call that service, passing in the desired entity ID and time from the input_datetime, so that the integration’s async_set_value method is invoked, writing the new charging schedule to the inverter via Modbus and the card updates.

I'm a HA newbie so apologies if there's an easier way.
ChatGPT o3-mini-high helped me!.

PS: Hi Steve!

Ian.

The solis_modbus __init__.py, as follows:

```
# IanJ
import asyncio
from datetime import datetime

# IanJ
from custom_components.solis_modbus.const import DOMAIN, TIME_ENTITIES

# IanJ
async def async_set_time_service(call: ServiceCall) -> None:
    """Service to update a Solis time entity."""
    entity_id = call.data.get("entity_id")
    new_time_str = call.data.get("time")

    if not entity_id or not new_time_str:
        _LOGGER.error("Missing entity_id or time parameter in service call")
        return

    try:
        # Try to parse time in HH:MM:SS format first, then fallback to HH:MM
        try:
            new_time = datetime.strptime(new_time_str, "%H:%M:%S").time()
        except ValueError:
            new_time = datetime.strptime(new_time_str, "%H:%M").time()
    except Exception as e:
        _LOGGER.error("Failed to parse time string '%s': %s", new_time_str, e)
        return

    found = False
    # Look through the registered time entities for one that matches the given entity_id
    for entity in call.hass.data.get(DOMAIN, {}).get(TIME_ENTITIES, []):
        if entity.entity_id == entity_id:
            await entity.async_set_value(new_time)
            found = True
            _LOGGER.debug("Set time for %s to %s", entity_id, new_time)
            break

    if not found:
        _LOGGER.error("Entity with id %s not found in solis_modbus TIME_ENTITIES", entity_id)

async def async_setup(hass: HomeAssistant, config: dict) -> bool:
    """Set up the Solis Modbus component."""
    # Register the custom service 'set_time'
    hass.services.async_register(DOMAIN, "set_time", async_set_time_service)
    _LOGGER.debug("Registered service %s.set_time", DOMAIN)
    return True
```

And then my automations.yaml as follows:

```
# Battery inverter charge time start/end (based on solar.forecast)
- alias: "Set Overnight Charging Schedule"
  description: "Determines overnight charging time based on tomorrow's solar forecast"
  mode: single
  trigger:
    - platform: time
      at: "23:30:00"
  action:
    - variables:
        solar_forecast: "{{ states('sensor.energy_production_tomorrow') | float(0) }}"

    - choose:
        - conditions:
            - condition: numeric_state
              entity_id: sensor.energy_production_tomorrow
              below: 3
          sequence:
            - service: input_datetime.set_datetime
              target:
                entity_id: input_datetime.charge_start
              data:
                time: "02:00"
            - service: input_datetime.set_datetime
              target:
                entity_id: input_datetime.charge_end
              data:
                time: "05:30"

        - conditions:
            - condition: numeric_state
              entity_id: sensor.energy_production_tomorrow
              below: 5
          sequence:
            - service: input_datetime.set_datetime
              target:
                entity_id: input_datetime.charge_start
              data:
                time: "02:00"
            - service: input_datetime.set_datetime
              target:
                entity_id: input_datetime.charge_end
              data:
                time: "05:00"

        - conditions:
            - condition: numeric_state
              entity_id: sensor.energy_production_tomorrow
              below: 7
          sequence:
            - service: input_datetime.set_datetime
              target:
                entity_id: input_datetime.charge_start
              data:
                time: "02:00"
            - service: input_datetime.set_datetime
              target:
                entity_id: input_datetime.charge_end
              data:
                time: "04:30"

        - conditions:
            - condition: numeric_state
              entity_id: sensor.energy_production_tomorrow
              below: 9
          sequence:
            - service: input_datetime.set_datetime
              target:
                entity_id: input_datetime.charge_start
              data:
                time: "02:00"
            - service: input_datetime.set_datetime
              target:
                entity_id: input_datetime.charge_end
              data:
                time: "04:00"

        - conditions:
            - condition: numeric_state
              entity_id: sensor.energy_production_tomorrow
              below: 12
          sequence:
            - service: input_datetime.set_datetime
              target:
                entity_id: input_datetime.charge_start
              data:
                time: "02:00"
            - service: input_datetime.set_datetime
              target:
                entity_id: input_datetime.charge_end
              data:
                time: "03:30"

      default:
        - service: input_datetime.set_datetime
          target:
            entity_id: input_datetime.charge_start
          data:
            time: "00:00"
        - service: input_datetime.set_datetime
          target:
            entity_id: input_datetime.charge_end
          data:
            time: "00:00"

    # Force Home Assistant to update the values
    - service: homeassistant.update_entity
      target:
        entity_id:
          - input_datetime.charge_start
          - input_datetime.charge_end

    # Log values to Home Assistant's system log
    - service: system_log.write
      data:
        message: >
          "Overnight Charging: Start Time - {{ states('input_datetime.charge_start') }}, 
          End Time - {{ states('input_datetime.charge_end') }}, 
          Solar Forecast - {{ solar_forecast }} kWh"
        level: info

    # Send a persistent notification with the values
    - service: persistent_notification.create
      data:
        title: "🔋 Overnight Charging Set"
        message: >
          Charging Schedule Updated:
          - Start: {{ states('input_datetime.charge_start') }}
          - End: {{ states('input_datetime.charge_end') }}
          - Solar Forecast: {{ solar_forecast }} kWh
        notification_id: "charging_schedule_update"

    # Update Solis Charge Start Time
    - service: solis_modbus.set_time
      data:
        entity_id: time.solis_s6_solis_time_charging_charge_start_slot_1
        time: "{{ states('input_datetime.charge_start') }}"

    - delay: '00:00:02'

    # Update Solis Charge End Time
    - service: solis_modbus.set_time
      data:
        entity_id: time.solis_s6_solis_time_charging_charge_end_slot_1
        time: "{{ states('input_datetime.charge_end') }}"

```
